import { useEffect, useMemo, useState } from 'react'
import { AnimatePresence, motion } from 'framer-motion'
import * as Icons from 'lucide-react'
import type { Entry, PlannerState, Project, Task, TaskStatus, UserProfile, View } from './types'
import { defaultProfile, initialState } from './data'
import { api } from './api'

const nav: {id: View; label: string; icon: keyof typeof Icons}[] = [
  {id:'dashboard',label:'Обзор',icon:'LayoutDashboard'}, {id:'projects',label:'Проекты',icon:'Layers3'},
  {id:'calendar',label:'Календарь',icon:'CalendarDays'}, {id:'ideas',label:'Идеи',icon:'Lightbulb'},
  {id:'research',label:'Исследования',icon:'FlaskConical'}, {id:'settings',label:'Настройки',icon:'Settings2'}
]
const statuses: TaskStatus[] = ['Backlog','Todo','In Progress','Done']
const statusRu: Record<TaskStatus,string> = {'Backlog':'Бэклог','Todo':'К выполнению','In Progress':'В работе','Done':'Готово'}
const uid = () => Math.random().toString(36).slice(2,9)
const formatDate = (s?: string) => s ? new Intl.DateTimeFormat('ru-RU',{day:'numeric',month:'short'}).format(new Date(s+'T12:00:00')) : ''
const todayKey = new Date().toISOString().slice(0,10)

function Icon({name,size=18}:{name:keyof typeof Icons|string,size?:number}) {
  const C = (Icons as unknown as Record<string, React.ComponentType<{size?:number;strokeWidth?:number}>>)[name] || Icons.Circle
  return <C size={size} strokeWidth={1.8}/>
}

function usePlanner() {
  const [state,setState] = useState<PlannerState>(()=>{ try { return JSON.parse(localStorage.getItem('founder-os')||'null') || initialState } catch { return initialState } })
  const [profile,setProfile] = useState<UserProfile>(()=>{ try { return JSON.parse(localStorage.getItem('founder-profile')||'null') || defaultProfile } catch { return defaultProfile } })
  const [ready,setReady]=useState(false)
  const [persistence,setPersistence]=useState<'postgres'|'local'>('local')
  useEffect(()=>{api.bootstrap(state,profile).then(data=>{setState(data.state?.projects?.length?data.state:state);setProfile(data.profile?.name?data.profile:profile);setPersistence(data.persistence as 'postgres'|'local')}).catch(()=>{}).finally(()=>setReady(true))},[])
  useEffect(()=>{if(!ready)return;localStorage.setItem('founder-os',JSON.stringify(state));const timer=setTimeout(()=>api.saveState(state).catch(()=>{}),500);return()=>clearTimeout(timer)},[state,ready])
  useEffect(()=>{if(!ready)return;localStorage.setItem('founder-profile',JSON.stringify(profile));const timer=setTimeout(()=>api.saveProfile(profile).catch(()=>{}),500);return()=>clearTimeout(timer)},[profile,ready])
  return [state,setState,profile,setProfile,persistence] as const
}

export default function App() {
  const [state,setState,profile,setProfile,persistence] = usePlanner()
  const [view,setView] = useState<View>('dashboard')
  const [projectId,setProjectId] = useState<string|null>(null)
  const [aiOpen,setAiOpen] = useState(false)
  const [mobileNav,setMobileNav] = useState(false)
  const current = state.projects.find(p=>p.id===projectId)
  const go = (v:View) => { setView(v); setProjectId(null); setMobileNav(false) }
  const updateProject = (next:Project) => setState(s=>({...s,projects:s.projects.map(p=>p.id===next.id?next:p)}))
  return <div className="app-shell">
    <div className="ambient one"/><div className="ambient two"/>
    <aside className={`sidebar ${mobileNav?'open':''}`}>
      <div className="brand"><div className="brand-mark"><Icons.Command size={19}/></div><div><b>FOUNDER</b><span>operating system</span></div></div>
      <nav>{nav.map(n=><button key={n.id} className={(view===n.id&&!projectId)?'active':''} onClick={()=>go(n.id)}><Icon name={n.icon}/><span>{n.label}</span>{n.id==='ideas'&&<em>{state.projects.reduce((a,p)=>a+p.ideas.length,0)}</em>}</button>)}</nav>
      <div className="side-projects"><div className="side-label">ПРОЕКТЫ <button onClick={()=>go('projects')}><Icons.Plus size={14}/></button></div>{state.projects.slice(0,5).map(p=><button key={p.id} className={projectId===p.id?'active':''} onClick={()=>{setProjectId(p.id);setView('projects');setMobileNav(false)}}><span className="project-dot" style={{background:p.color}}/>{p.name}<small>{p.progress}%</small></button>)}</div>
      <div className="profile"><div className="avatar">Д</div><div><b>Денис</b><span>Founder</span></div><Icons.ChevronUp size={15}/></div>
    </aside>
    <main>
      <header><button className="mobile-menu" onClick={()=>setMobileNav(!mobileNav)}><Icons.Menu/></button><div className="crumb"><span>Founder OS</span><Icons.ChevronRight size={14}/><b>{current?.name || nav.find(n=>n.id===view)?.label}</b></div><div className="header-actions"><div className="sync"><span/> Локально сохранено</div><button className="icon-button"><Icons.Search size={18}/></button><button className="icon-button"><Icons.Bell size={18}/><i/></button></div></header>
      <div className="content"><AnimatePresence mode="wait"><motion.div key={projectId||view} initial={{opacity:0,y:8}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-6}} transition={{duration:.22}}>
        {current ? <ProjectView project={current} update={updateProject}/> : view==='dashboard' ? <Dashboard state={state} setState={setState} openProject={setProjectId}/> : view==='projects' ? <Projects state={state} open={setProjectId}/> : view==='calendar' ? <Calendar state={state}/> : view==='ideas' ? <Ideas state={state} setState={setState}/> : view==='settings' ? <ProfileView profile={profile} setProfile={setProfile} persistence={persistence} products={state.projects}/> : <EmptyView view={view}/>} 
      </motion.div></AnimatePresence></div>
    </main>
    <button className={`ai-fab ${aiOpen?'opened':''}`} onClick={()=>setAiOpen(!aiOpen)}><Icons.Sparkles size={18}/><span>Спросить AI</span></button>
    <AnimatePresence>{aiOpen&&<AiPanel project={current} state={state} profile={profile} close={()=>setAiOpen(false)}/>}</AnimatePresence>
  </div>
}

function PageTitle({eyebrow,title,subtitle,action}:{eyebrow:string,title:string,subtitle:string,action?:React.ReactNode}) { return <div className="page-title"><div><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{subtitle}</p></div>{action}</div> }

function Dashboard({state,setState,openProject}:{state:PlannerState,setState:React.Dispatch<React.SetStateAction<PlannerState>>,openProject:(id:string)=>void}) {
  const tasks=state.projects.flatMap(p=>p.tasks.map(t=>({...t,project:p})))
  const due=tasks.filter(t=>t.status!=='Done'&&t.deadline).sort((a,b)=>a.deadline!.localeCompare(b.deadline!)).slice(0,4)
  const active=tasks.filter(t=>t.status==='In Progress')
  const ideas=state.projects.flatMap(p=>p.ideas.map(i=>({...i,project:p})))
  const greeting = new Date().getHours()<12?'Доброе утро':new Date().getHours()<18?'Добрый день':'Добрый вечер'
  return <>
    <PageTitle eyebrow={new Intl.DateTimeFormat('ru-RU',{weekday:'long',day:'numeric',month:'long'}).format(new Date())} title={`${greeting}, Денис`} subtitle="Вот что сегодня двигает компанию вперёд." action={<button className="primary"><Icons.Plus size={17}/> Быстрая запись</button>}/>
    <section className="focus-card"><div className="focus-glow"/><div className="focus-icon"><Icons.Crosshair/></div><div className="focus-copy"><span>ГЛАВНЫЙ ФОКУС СЕГОДНЯ</span><input value={state.focus} onChange={e=>setState(s=>({...s,focus:e.target.value}))}/><small><Icons.Sparkles size={13}/> Максимальный вклад: завершить ключевой результат до переключения контекста</small></div><div className="focus-progress"><div><b>{active.length}</b><span>в работе</span></div><button><Icons.ArrowUpRight/></button></div></section>
    <div className="stats-grid">
      <Stat icon="CircleCheckBig" color="cyan" value={tasks.filter(t=>t.deadline===todayKey&&t.status!=='Done').length.toString().padStart(2,'0')} label="Задачи на сегодня" note={`${active.length} сейчас в работе`}/>
      <Stat icon="Lightbulb" color="violet" value={ideas.length.toString().padStart(2,'0')} label="Свежие идеи" note="Есть что разобрать"/>
      <Stat icon="Timer" color="orange" value={due.length.toString().padStart(2,'0')} label="Ближайшие дедлайны" note="На горизонте 7 дней"/>
      <Stat icon="TrendingUp" color="green" value={`${Math.round(state.projects.reduce((a,p)=>a+p.progress,0)/state.projects.length)}%`} label="Общий прогресс" note="По всем направлениям"/>
    </div>
    <div className="dashboard-grid"><section className="panel progress-panel"><PanelHead title="Пульс компании" subtitle="Прогресс ключевых направлений" action="Все проекты"/><div className="progress-list">{state.projects.map(p=><button key={p.id} onClick={()=>openProject(p.id)}><div className="project-icon" style={{color:p.color,background:`${p.color}15`}}><Icon name={p.icon}/></div><div className="bar-copy"><div><b>{p.name}</b><span>{p.progress}%</span></div><div className="bar"><i style={{width:`${p.progress}%`,background:p.color,boxShadow:`0 0 14px ${p.color}80`}}/></div></div></button>)}</div></section>
    <section className="panel deadline-panel"><PanelHead title="Ближайшие дедлайны" subtitle="Требуют внимания"/><div className="deadline-list">{due.map(t=><div key={t.id}><span className={`priority ${t.priority.toLowerCase()}`}/><div><b>{t.title}</b><small>{t.project.name}</small></div><time className={t.deadline!<=todayKey?'urgent':''}>{t.deadline===todayKey?'Сегодня':formatDate(t.deadline)}</time></div>)}</div><button className="panel-footer">Открыть календарь <Icons.ArrowRight size={15}/></button></section></div>
  </>
}

function Stat({icon,color,value,label,note}:{icon:string,color:string,value:string,label:string,note:string}) { return <div className="stat"><div className={`stat-icon ${color}`}><Icon name={icon}/></div><div><b>{value}</b><span>{label}</span><small>{note}</small></div><Icons.MoreHorizontal className="more" size={17}/></div> }
function PanelHead({title,subtitle,action}:{title:string,subtitle:string,action?:string}) { return <div className="panel-head"><div><h3>{title}</h3><p>{subtitle}</p></div>{action&&<button>{action}<Icons.ChevronRight size={14}/></button>}</div> }

function Projects({state,open}:{state:PlannerState,open:(id:string)=>void}) { return <><PageTitle eyebrow="РАБОЧИЕ КОНТУРЫ" title="Проекты" subtitle="Каждый проект — отдельное направление роста компании." action={<button className="primary"><Icons.Plus size={17}/> Новый проект</button>}/><div className="projects-grid">{state.projects.map((p,i)=><motion.button className="project-card" key={p.id} onClick={()=>open(p.id)} initial={{opacity:0,y:10}} animate={{opacity:1,y:0}} transition={{delay:i*.03}}><div className="project-top"><div className="large-project-icon" style={{color:p.color,background:`${p.color}15`,boxShadow:`inset 0 0 22px ${p.color}10`}}><Icon name={p.icon} size={23}/></div><Icons.ArrowUpRight size={18}/></div><h3>{p.name}</h3><p>{p.description}</p><div className="project-meta"><span>{p.tasks.filter(t=>t.status!=='Done').length} задач</span><span>{p.ideas.length} идей</span></div><div className="project-progress"><div><span>Прогресс</span><b>{p.progress}%</b></div><div className="bar"><i style={{width:`${p.progress}%`,background:p.color,boxShadow:`0 0 12px ${p.color}70`}}/></div></div></motion.button>)}</div></> }

function ProjectView({project,update}:{project:Project,update:(p:Project)=>void}) {
  const [tab,setTab]=useState<'tasks'|'ideas'|'improvements'|'notes'>('tasks'); const [adding,setAdding]=useState(false); const [text,setText]=useState('')
  const add=()=>{if(!text.trim())return; if(tab==='tasks') update({...project,tasks:[...project.tasks,{id:uid(),title:text,status:'Todo',priority:'Medium',tags:[]}]}); else update({...project,[tab]:[...project[tab],{id:uid(),title:text,createdAt:new Date().toISOString()}]});setText('');setAdding(false)}
  const move=(task:Task,status:TaskStatus)=>update({...project,tasks:project.tasks.map(t=>t.id===task.id?{...t,status}:t)})
  return <><div className="project-hero"><div className="large-project-icon" style={{color:project.color,background:`${project.color}15`}}><Icon name={project.icon} size={25}/></div><div><span className="eyebrow">ПРОЕКТ</span><h1>{project.name}</h1><p>{project.description}</p></div><div className="hero-progress"><b>{project.progress}%</b><span>общий прогресс</span></div><button className="icon-button"><Icons.MoreHorizontal/></button></div>
  <div className="tabs">{(['tasks','ideas','improvements','notes'] as const).map(t=><button className={tab===t?'active':''} onClick={()=>setTab(t)} key={t}>{t==='tasks'?'Задачи':t==='ideas'?'Идеи':t==='improvements'?'Улучшения':'Заметки'}<span>{project[t].length}</span></button>)}<button className="add-tab" onClick={()=>setAdding(true)}><Icons.Plus size={16}/> Добавить</button></div>
  {adding&&<div className="quick-add"><input autoFocus placeholder={tab==='tasks'?'Что нужно сделать?':'Запишите мысль...'} value={text} onChange={e=>setText(e.target.value)} onKeyDown={e=>e.key==='Enter'&&add()}/><button onClick={add}>Добавить</button><button onClick={()=>setAdding(false)}><Icons.X size={16}/></button></div>}
  {tab==='tasks'?<div className="kanban">{statuses.map(s=><div className="column" key={s}><div className="column-head"><span className={`status-dot s-${s.replaceAll(' ','-')}`}/><b>{statusRu[s]}</b><em>{project.tasks.filter(t=>t.status===s).length}</em></div>{project.tasks.filter(t=>t.status===s).map(t=><div className="task-card" key={t.id}><div className="task-priority"><span className={`priority ${t.priority.toLowerCase()}`}/>{t.priority==='High'?'Высокий':t.priority==='Medium'?'Средний':'Низкий'}</div><h4>{t.title}</h4>{t.description&&<p>{t.description}</p>}<div className="task-bottom">{t.deadline?<span><Icons.Calendar size={13}/>{formatDate(t.deadline)}</span>:<span/>}<select value={t.status} onChange={e=>move(t,e.target.value as TaskStatus)}>{statuses.map(x=><option key={x}>{x}</option>)}</select></div></div>)}</div>)}</div>:<EntryList entries={project[tab]} empty={tab==='ideas'?'Идей пока нет — поймайте первую.':tab==='notes'?'Заметок пока нет.':'Улучшений пока нет.'}/>}</> 
}

function EntryList({entries,empty}:{entries:Entry[],empty:string}) { return entries.length?<div className="entry-grid">{entries.map(e=><div className="entry-card" key={e.id}><div><Icons.Sparkles size={16}/><span>{new Intl.DateTimeFormat('ru-RU',{day:'numeric',month:'long'}).format(new Date(e.createdAt))}</span></div><h3>{e.title}</h3>{e.body&&<p>{e.body}</p>}<button><Icons.ArrowUpRight size={17}/></button></div>)}</div>:<div className="empty"><Icons.CircleDashed/><h3>{empty}</h3><p>Добавление занимает несколько секунд.</p></div> }

function Calendar({state}:{state:PlannerState}) { const tasks=state.projects.flatMap(p=>p.tasks.filter(t=>t.deadline).map(t=>({...t,project:p}))).sort((a,b)=>a.deadline!.localeCompare(b.deadline!)); const days=Array.from({length:14},(_,i)=>{const d=new Date();d.setDate(d.getDate()+i);return d}); return <><PageTitle eyebrow="ВРЕМЕННАЯ ЛИНИЯ" title="Календарь" subtitle="Загрузка и дедлайны на ближайшие две недели."/><div className="calendar-strip">{days.map((d,i)=>{const k=d.toISOString().slice(0,10), count=tasks.filter(t=>t.deadline===k).length;return <div className={i===0?'today':''} key={k}><span>{new Intl.DateTimeFormat('ru-RU',{weekday:'short'}).format(d)}</span><b>{d.getDate()}</b>{count>0&&<i>{count}</i>}</div>})}</div><section className="panel timeline"><PanelHead title="Предстоящие события" subtitle={`${tasks.length} запланировано`}/>{tasks.map(t=><div className="timeline-row" key={t.id}><time><b>{new Date(t.deadline!+'T12:00').getDate()}</b><span>{new Intl.DateTimeFormat('ru-RU',{month:'short'}).format(new Date(t.deadline!+'T12:00'))}</span></time><span className="timeline-line" style={{background:t.project.color}}/><div><h4>{t.title}</h4><p>{t.project.name} · {statusRu[t.status]}</p></div><span className={`badge ${t.priority.toLowerCase()}`}>{t.priority==='High'?'Высокий':t.priority==='Medium'?'Средний':'Низкий'}</span></div>)}</section></> }

function Ideas({state,setState}:{state:PlannerState,setState:React.Dispatch<React.SetStateAction<PlannerState>>}) { const [text,setText]=useState('');const [pid,setPid]=useState(state.projects[0].id); const all=state.projects.flatMap(p=>p.ideas.map(i=>({...i,project:p}))); const add=()=>{if(!text.trim())return;setState(s=>({...s,projects:s.projects.map(p=>p.id===pid?{...p,ideas:[{id:uid(),title:text,createdAt:new Date().toISOString()},...p.ideas]}:p)}));setText('')}; return <><PageTitle eyebrow="БАНК ВОЗМОЖНОСТЕЙ" title="Идеи" subtitle="Быстрый захват мыслей без потери контекста."/><div className="idea-capture"><Icons.Lightbulb/><input value={text} onChange={e=>setText(e.target.value)} onKeyDown={e=>e.key==='Enter'&&add()} placeholder="Какая идея появилась?"/><select value={pid} onChange={e=>setPid(e.target.value)}>{state.projects.map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select><button onClick={add}>Сохранить</button></div><div className="entry-grid">{all.map(e=><div className="entry-card" key={e.id}><div><span className="project-dot" style={{background:e.project.color}}/><span>{e.project.name}</span></div><h3>{e.title}</h3><p>Добавлено {formatDate(e.createdAt.slice(0,10))}</p><button><Icons.ArrowUpRight size={17}/></button></div>)}</div></> }

function EmptyView({view}:{view:View}) { const research=view==='research'; return <><PageTitle eyebrow="FOUNDER OS" title={research?'Исследования':'Настройки'} subtitle={research?'Материалы, гипотезы и выводы в одном месте.':'Персонализация локального рабочего пространства.'}/><div className="empty"><Icon name={research?'FlaskConical':'Settings2'} size={30}/><h3>{research?'Раздел готов к вашим исследованиям':'Всё уже настроено для старта'}</h3><p>{research?'Добавление материалов появится в следующей итерации MVP.':'Данные хранятся только в этом браузере.'}</p></div></> }

function ProfileView({profile,setProfile,persistence,products}:{profile:UserProfile,setProfile:React.Dispatch<React.SetStateAction<UserProfile>>,persistence:string,products:Project[]}) { const field=(key:keyof UserProfile,value:string|string[])=>setProfile(p=>({...p,[key]:value})); return <><PageTitle eyebrow="ПАМЯТЬ FOUNDER AI" title="Профиль основателя" subtitle="Этот контекст учитывается в каждом разговоре с AI." action={<div className={`storage-badge ${persistence}`}><Icons.Database size={14}/>{persistence==='postgres'?'PostgreSQL подключён':'Локальный режим'}</div>}/><div className="profile-layout"><section className="panel profile-form"><PanelHead title="Кто вы" subtitle="Личный и профессиональный контекст"/><label>Имя<input value={profile.name} onChange={e=>field('name',e.target.value)}/></label><label>Роль<input value={profile.role} onChange={e=>field('role',e.target.value)}/></label><label className="wide">О вас<textarea value={profile.bio} onChange={e=>field('bio',e.target.value)}/></label><label className="wide">Видение<textarea value={profile.vision} onChange={e=>field('vision',e.target.value)}/></label><label className="wide">Цели — по одной на строку<textarea value={profile.goals.join('\n')} onChange={e=>field('goals',e.target.value.split('\n').filter(Boolean))}/></label><label>Ограничения<textarea value={profile.constraints} onChange={e=>field('constraints',e.target.value)}/></label><label>Стиль работы<textarea value={profile.workingStyle} onChange={e=>field('workingStyle',e.target.value)}/></label><div className="autosave"><Icons.CloudCog size={15}/> Изменения сохраняются автоматически</div></section><aside className="panel memory-card"><PanelHead title="Память о продуктах" subtitle={`${products.length} направлений`}/>{products.map(p=><div className="memory-product" key={p.id}><span className="project-dot" style={{background:p.color}}/><div><b>{p.name}</b><small>{p.description}</small></div><em>{p.progress}%</em></div>)}</aside></div></> }

function AiPanel({project,state,profile,close}:{project?:Project,state:PlannerState,profile:UserProfile,close:()=>void}) { const [query,setQuery]=useState(''); const [messages,setMessages]=useState<{role:'user'|'assistant';content:string}[]>([]); const [conversationId,setConversationId]=useState<string>(); const [loading,setLoading]=useState(false); const context=project?.name||'вся компания'; const welcome=useMemo(()=>`Я знаю ваш профиль, цели и ${state.projects.length} продуктов. Сейчас работаем в контексте: ${context}. Чем помочь?`,[context,state.projects.length]); const send=async()=>{const message=query.trim();if(!message||loading)return;setMessages(m=>[...m,{role:'user',content:message}]);setQuery('');setLoading(true);try{const result=await api.chat({message,context,conversationId,state,profile});setConversationId(result.conversationId);setMessages(m=>[...m,{role:'assistant',content:result.answer}])}catch(e){setMessages(m=>[...m,{role:'assistant',content:e instanceof Error?`${e.message}. Добавьте OPENAI_API_KEY в Railway Variables.`:'Не удалось связаться с AI.'}])}finally{setLoading(false)}}; return <motion.aside className="ai-panel" initial={{opacity:0,x:30}} animate={{opacity:1,x:0}} exit={{opacity:0,x:30}}><div className="ai-head"><div className="ai-orb"><Icons.Sparkles/></div><div><b>Founder AI · GPT</b><span><i/> Контекст: {context}</span></div><button onClick={close}><Icons.X/></button></div><div className="ai-body"><div className="ai-context"><Icons.ScanSearch/><span>Учитываю профиль, продукты, задачи и прошлые сообщения.</span></div><div className="ai-message">{welcome}</div>{messages.map((m,i)=><div className={m.role==='user'?'user-message':'ai-message'} key={i}>{m.content}</div>)}{loading&&<div className="ai-message typing"><i/><i/><i/></div>}</div><div className="ai-prompts"><button onClick={()=>setQuery('Что сейчас важнее всего?')}>Что важнее всего?</button><button onClick={()=>setQuery('Где главный риск?')}>Где главный риск?</button></div><div className="ai-input"><textarea placeholder="Спросите о следующем лучшем действии..." value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}}}/><button onClick={send} disabled={loading}><Icons.ArrowUp size={17}/></button></div></motion.aside> }
