import { useMemo, useState, type FormEvent } from 'react'
import { ArrowRight, BrainCircuit, Calendar, CheckCircle2, Filter, GitBranch, Plus, RotateCcw, Scale, ShieldAlert, X } from 'lucide-react'
import type { Decision, Project } from './types'

const labels:Record<Decision['status'],string>={captured:'Зафиксировано',committed:'Принято',under_review:'На проверке',validated:'Подтверждено',reversed:'Пересмотрено'}
const reversibility={reversible:'Обратимое',costly:'Дорого отменять',irreversible:'Необратимое'}
const uid=()=>crypto.randomUUID?.()||Math.random().toString(36).slice(2)
const dateText=(value?:string)=>value?new Intl.DateTimeFormat('ru-RU',{day:'numeric',month:'long'}).format(new Date(value+'T12:00')):'Без даты'

export default function Decisions({items,onChange,userId,projects}:{items:Decision[];onChange:(items:Decision[])=>void;userId:string;projects:Project[]}){
  const [open,setOpen]=useState(false),[review,setReview]=useState<Decision>(),[filter,setFilter]=useState<'active'|'due'|'all'>('active')
  const today=new Date().toISOString().slice(0,10)
  const due=items.filter(x=>x.reviewDate&&x.reviewDate<=today&&!['validated','reversed'].includes(x.status)).length
  const visible=useMemo(()=>items.filter(x=>filter==='all'||filter==='due'?(filter==='all'||Boolean(x.reviewDate&&x.reviewDate<=today&&!['validated','reversed'].includes(x.status))):!['validated','reversed'].includes(x.status)),[items,filter,today])
  const submit=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);onChange([{id:uid(),title:String(f.get('title')),rationale:String(f.get('rationale')),expectedOutcome:String(f.get('expectedOutcome')),confidence:Number(f.get('confidence')),reviewDate:String(f.get('reviewDate')||'')||undefined,status:'committed',createdAt:new Date().toISOString(),createdBy:userId,projectId:String(f.get('projectId')||'')||undefined,reversibility:f.get('reversibility') as Decision['reversibility'],assumptions:String(f.get('assumptions')||''),premortem:String(f.get('premortem')||'')},...items]);setOpen(false)}
  const finishReview=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();if(!review)return;const f=new FormData(e.currentTarget),status=f.get('status') as Decision['status'];onChange(items.map(x=>x.id===review.id?{...x,status,actualOutcome:String(f.get('actualOutcome')),reviewNote:String(f.get('reviewNote')),reasoningQuality:f.get('reasoningQuality') as Decision['reasoningQuality']}:x));setReview(undefined)}
  return <><div className="decision-title"><div><span>ТРЕНАЖЁР СУЖДЕНИЯ</span><h1>Решения</h1><p>Сохраняйте ход мысли до того, как станет известен результат. При проверке отделяйте качество рассуждения от удачи.</p></div><button onClick={()=>setOpen(true)}><Plus/>Зафиксировать решение</button></div>
    <div className="decision-metrics"><article><BrainCircuit/><b>{items.length}</b><span>в памяти</span></article><article className={due?'warn':''}><Calendar/><b>{due}</b><span>пора проверить</span></article><article><Scale/><b>{items.length?Math.round(items.reduce((n,x)=>n+x.confidence,0)/items.length):0}%</b><span>средняя уверенность</span></article></div>
    <div className="decision-filters"><Filter/>{(['active','due','all'] as const).map(x=><button className={filter===x?'active':''} onClick={()=>setFilter(x)} key={x}>{x==='active'?'Действующие':x==='due'?'На проверку':'Все'}</button>)}</div>
    <div className="decision-feed">{visible.map(x=>{const project=projects.find(p=>p.id===x.projectId);return <article key={x.id}><header><span className={`decision-status ${x.status}`}>{labels[x.status]}</span><time>{dateText(x.createdAt.slice(0,10))}</time></header><h3>{x.title}</h3>{project&&<div className="decision-project"><i style={{background:project.color}}/>{project.name}</div>}<div className="decision-why"><small>ПОЧЕМУ</small><p>{x.rationale}</p></div>{x.assumptions&&<div className="decision-assumption"><small>КЛЮЧЕВОЕ ДОПУЩЕНИЕ</small><p>{x.assumptions}</p></div>}<div className="decision-expect"><small>ОЖИДАЕМЫЙ ИСХОД</small><p>{x.expectedOutcome}</p></div>{x.actualOutcome&&<div className="decision-actual"><small>ЧТО ПРОИЗОШЛО</small><p>{x.actualOutcome}</p></div>}<footer><div><span>Уверенность</span><b>{x.confidence}%</b><i><em style={{width:`${x.confidence}%`}}/></i></div><div><span>{x.reversibility?reversibility[x.reversibility]:'Проверка'}</span><b>{dateText(x.reviewDate)}</b></div>{!['validated','reversed'].includes(x.status)&&<button onClick={()=>setReview({...x,status:'under_review'})}>Проверить <ArrowRight/></button>}</footer></article>})}{!visible.length&&<div className="decision-empty"><BrainCircuit/><h3>{items.length?'В этом фильтре пусто':'Первое решение создаст память'}</h3><p>Фиксируйте реальный выбор, причины, допущения и ожидаемый исход. Система вернёт его на проверку.</p><button onClick={()=>setOpen(true)}><Plus/>Зафиксировать</button></div>}</div>
    {open&&<div className="decision-modal" onMouseDown={e=>e.target===e.currentTarget&&setOpen(false)}><section><header><div><span>DECISION CAPTURE</span><h2>Зафиксировать решение</h2></div><button onClick={()=>setOpen(false)}><X/></button></header><form onSubmit={submit}><label>Какое решение принято?<input name="title" autoFocus required placeholder="Один конкретный выбор"/></label><div><label>Проект<select name="projectId"><option value="">Всё пространство</option>{projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>Обратимость<select name="reversibility" defaultValue="reversible"><option value="reversible">Можно легко отменить</option><option value="costly">Отмена будет дорогой</option><option value="irreversible">Практически необратимо</option></select></label></div><label>Почему это кажется верным?<textarea name="rationale" required placeholder="Факты и альтернативы, которые вы рассмотрели"/></label><label>Ключевое допущение<textarea name="assumptions" placeholder="Что должно оказаться правдой?"/></label><label>Какой исход вы ожидаете?<textarea name="expectedOutcome" required placeholder="Наблюдаемый результат и срок"/></label><label>Короткий премортем<textarea name="premortem" placeholder="Если решение провалилось — почему это могло случиться?"/></label><div><label>Уверенность<select name="confidence" defaultValue="70"><option value="50">50% — скорее да</option><option value="70">70% — уверен</option><option value="90">90% — почти уверен</option></select></label><label>Когда проверить?<input name="reviewDate" type="date"/></label></div><aside><Scale/><p>Не подгоняйте запись под красивый ответ. Ценность возникает, когда ожидание можно честно сравнить с реальностью.</p></aside><button className="decision-submit">Зафиксировать <ArrowRight/></button></form></section></div>}
    {review&&<div className="decision-modal review-modal" onMouseDown={e=>e.target===e.currentTarget&&setReview(undefined)}><section><header><div><span>DECISION REVIEW</span><h2>Проверить решение</h2></div><button onClick={()=>setReview(undefined)}><X/></button></header><form onSubmit={finishReview}><div className="review-original"><GitBranch/><div><b>{review.title}</b><p>Ожидали: {review.expectedOutcome}</p></div></div><label>Что произошло на самом деле?<textarea name="actualOutcome" required placeholder="Наблюдаемый исход без интерпретации"/></label><label>Качество исходного рассуждения<select name="reasoningQuality" defaultValue="sound"><option value="sound">Логика была качественной</option><option value="unclear">Недостаточно данных</option><option value="flawed">В рассуждении была ошибка</option></select></label><label>Что перенесём в следующее решение?<textarea name="reviewNote" required placeholder="Принцип, сигнал или ошибка"/></label><label>Итог<select name="status" defaultValue="validated"><option value="validated">Подтвердить решение</option><option value="reversed">Пересмотреть решение</option></select></label><aside><ShieldAlert/><p>Хороший результат мог быть удачей, а плохой — следствием внешнего события. Оценивайте процесс отдельно.</p></aside><button className="decision-submit"><CheckCircle2/>Завершить проверку</button></form></section></div>}
  </>
}
