import { useEffect, useMemo, useState, type Dispatch, type SetStateAction } from 'react'
import { BadgeCheck, CircleAlert, DatabaseZap, Link2, LockKeyhole, LogOut, Save, ShieldCheck, UserRound } from 'lucide-react'
import { api } from './api'
import type { AuthUser, FinanceStatus, UserProfile } from './types'

type Tab='context'|'finance'|'security'

export default function ProfileSettings({profile,setProfile,auth,setAuth,logout}:{profile:UserProfile;setProfile:Dispatch<SetStateAction<UserProfile>>;auth:AuthUser;setAuth:Dispatch<SetStateAction<AuthUser|null|undefined>>;logout:()=>void}){
  const [tab,setTab]=useState<Tab>('context')
  const [saveStatus,setSaveStatus]=useState<'idle'|'saving'|'saved'|'error'>('idle')
  const [finance,setFinance]=useState<FinanceStatus>()
  const [financeId,setFinanceId]=useState(auth.externalUserId||'')
  const [financeBusy,setFinanceBusy]=useState(false)
  const [financeError,setFinanceError]=useState('')
  const completion=useMemo(()=>{const values=[profile.name,profile.role,profile.bio,profile.vision,profile.constraints,profile.workingStyle,profile.goals.length];return Math.round(values.filter(Boolean).length/values.length*100)},[profile])
  const field=(key:keyof UserProfile,value:string|string[])=>setProfile(p=>({...p,[key]:value}))
  const loadFinance=()=>api.financeStatus().then(setFinance).catch(()=>{})
  useEffect(()=>{loadFinance()},[auth.externalUserId])
  const saveProfile=async()=>{setSaveStatus('saving');try{await api.saveProfile(profile);setAuth(user=>user?{...user,displayName:profile.name}:user);setSaveStatus('saved');window.setTimeout(()=>setSaveStatus('idle'),2200)}catch{setSaveStatus('error')}}
  const saveFinance=async()=>{setFinanceBusy(true);setFinanceError('');try{const result=await api.saveAccount(financeId);setAuth(user=>user?{...user,externalUserId:result.externalUserId}:user);await loadFinance()}catch(e){setFinanceError(e instanceof Error?e.message:'Не удалось связать Finance')}finally{setFinanceBusy(false)}}

  return <>
    <div className="settings-title"><div><span>ЛИЧНЫЙ КОНТЕКСТ</span><h1>Профиль и настройки</h1><p>Эти данные помогают Founder AI давать ответы именно для вашей ситуации.</p></div><div className="profile-completion"><b>{completion}%</b><span>контекст заполнен</span><i><em style={{width:`${completion}%`}}/></i></div></div>
    <div className="settings-layout">
      <aside className="settings-nav"><div className="settings-identity"><span>{(profile.name||auth.displayName).slice(0,1)}</span><div><b>{profile.name||auth.displayName}</b><small>@{auth.publicId}</small></div></div><nav><button className={tab==='context'?'active':''} onClick={()=>setTab('context')}><UserRound/><div><b>Контекст</b><small>Кто вы и куда идёте</small></div></button><button className={tab==='finance'?'active':''} onClick={()=>setTab('finance')}><DatabaseZap/><div><b>Finance</b><small>Связь между продуктами</small></div></button><button className={tab==='security'?'active':''} onClick={()=>setTab('security')}><LockKeyhole/><div><b>Безопасность</b><small>ID и активная сессия</small></div></button></nav></aside>
      <section className="settings-content">
        {tab==='context'&&<><header><div><span>ПРОФИЛЬ ДЛЯ AI</span><h2>Расскажите только важное</h2><p>Не биография ради биографии: цели, ограничения и стиль принятия решений.</p></div><button onClick={saveProfile} disabled={saveStatus==='saving'}><Save/>{saveStatus==='saving'?'Сохраняем':saveStatus==='saved'?'Сохранено':saveStatus==='error'?'Ошибка':'Сохранить'}</button></header><div className="settings-form"><label>Как к вам обращаться<input value={profile.name} onChange={e=>field('name',e.target.value)} placeholder="Имя"/></label><label>Ваша роль<input value={profile.role} onChange={e=>field('role',e.target.value)} placeholder="Основатель, руководитель, родитель…"/></label><label className="wide">Коротко о вас<textarea value={profile.bio} onChange={e=>field('bio',e.target.value)} placeholder="Чем вы занимаетесь и за что отвечаете?"/></label><label className="wide">Куда вы идёте<textarea value={profile.vision} onChange={e=>field('vision',e.target.value)} placeholder="Как выглядит желаемое состояние через 1–3 года?"/></label><label className="wide">Текущие цели <small>по одной на строку</small><textarea value={profile.goals.join('\n')} onChange={e=>field('goals',e.target.value.split('\n').map(x=>x.trim()).filter(Boolean))} placeholder={'Запустить продукт\nСнизить операционную нагрузку'}/></label><label>Ограничения<textarea value={profile.constraints} onChange={e=>field('constraints',e.target.value)} placeholder="Время, деньги, обязательства"/></label><label>Стиль работы<textarea value={profile.workingStyle} onChange={e=>field('workingStyle',e.target.value)} placeholder="Как вы предпочитаете думать и действовать?"/></label></div></>}
        {tab==='finance'&&<><header><div><span>ИНТЕГРАЦИЯ</span><h2>Связь с Finance</h2><p>Разделяем идентичность пользователя и реальный доступ к финансовым данным.</p></div></header><div className={`finance-status-card ${finance?.mode||'identity'}`}><span>{finance?.linked?<BadgeCheck/>:<Link2/>}</span><div><b>{finance?.linked?'Finance ID связан':'Finance не связан'}</b><p>{finance?.message||'Добавьте ID пользователя из Finance.'}</p></div><em>{finance?.mode==='live'?'LIVE DATA':finance?.linked?'IDENTITY ONLY':'OFF'}</em></div><div className="finance-connect-form"><label>Finance user ID<input value={financeId} onChange={e=>setFinanceId(e.target.value)} placeholder="ID из приложения Finance"/></label><button onClick={saveFinance} disabled={financeBusy}><Link2/>{financeBusy?'Проверяем…':finance?.linked?'Обновить связь':'Связать профиль'}</button></div>{financeError&&<div className="finance-error"><CircleAlert/>{financeError}</div>}<aside className="integration-explainer"><CircleAlert/><div><b>Что доступно сейчас</b><p>{finance?.mode==='live'?'Канал Finance настроен. Founder AI сможет получать только разрешённые финансовые данные через серверный коннектор.':'Сейчас ID объединяет вашу личность между приложениями. Суммы, счета и транзакции в Planner не передаются — AI не будет их выдумывать.'}</p></div></aside></>}
        {tab==='security'&&<><header><div><span>АККАУНТ</span><h2>Безопасность и доступ</h2><p>Основные данные входа и состояние текущей сессии.</p></div></header><div className="security-list"><article><span><UserRound/></span><div><b>Planner ID</b><p>@{auth.publicId}</p></div><em>Постоянный</em></article><article><span><ShieldCheck/></span><div><b>Роль в пространстве</b><p>{auth.role==='owner'?'Владелец с полным доступом':'Участник с назначенными правами'}</p></div><em>{auth.role==='owner'?'OWNER':'MEMBER'}</em></article><article><span><LockKeyhole/></span><div><b>Текущая сессия</b><p>Защищённая HttpOnly cookie · срок 30 дней</p></div><em>АКТИВНА</em></article></div><button className="settings-logout" onClick={logout}><LogOut/>Выйти на этом устройстве</button></>}
      </section>
    </div>
  </>
}
