import { useMemo, useState, type FormEvent } from 'react'
import { Calendar, FileText, FolderKanban, Lightbulb, Plus, SquareCheckBig, X } from 'lucide-react'
import { motion } from 'framer-motion'
import type { Entry, Project, Task } from './types'

type CaptureType='task'|'ideas'|'notes'
const uid=()=>crypto.randomUUID?.()||Math.random().toString(36).slice(2)

export default function QuickCapture({projects,userId,close,save}:{projects:Project[];userId:string;close:()=>void;save:(projectId:string,type:CaptureType,data:Task|Entry)=>void}){
  const [type,setType]=useState<CaptureType>('task')
  const [projectId,setProjectId]=useState(projects[0]?.id||'')
  const current=useMemo(()=>projects.find(p=>p.id===projectId),[projects,projectId])
  const submit=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget),title=String(f.get('title')).trim(),body=String(f.get('body')||'');if(!title||!projectId)return;if(type==='task')save(projectId,type,{id:uid(),title,description:body,status:'Todo',priority:f.get('priority') as Task['priority'],deadline:String(f.get('deadline')||'')||undefined,assignee:String(f.get('assignee')||'').replace(/^@/,'')||undefined,tags:[]});else save(projectId,type,{id:uid(),title,body,createdAt:new Date().toISOString()})}
  return <motion.div className="capture-backdrop" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} onMouseDown={e=>e.target===e.currentTarget&&close()}><motion.section className="quick-capture" initial={{opacity:0,y:18,scale:.98}} animate={{opacity:1,y:0,scale:1}} exit={{opacity:0,y:18,scale:.98}}><header><div><span>БЫСТРАЯ ЗАПИСЬ</span><h2>{type==='task'?'Новая задача':type==='ideas'?'Новая идея':'Новая заметка'}</h2></div><button onClick={close}><X/></button></header><div className="capture-types"><button className={type==='task'?'active':''} onClick={()=>setType('task')}><SquareCheckBig/>Задача</button><button className={type==='ideas'?'active':''} onClick={()=>setType('ideas')}><Lightbulb/>Идея</button><button className={type==='notes'?'active':''} onClick={()=>setType('notes')}><FileText/>Заметка</button></div>{!projects.length?<div className="capture-no-project"><FolderKanban/><h3>Сначала нужен проект</h3><p>Каждая запись должна иметь контекст и владельца.</p><button onClick={close}>Вернуться</button></div>:<form onSubmit={submit}><label className="wide">Проект<select value={projectId} onChange={e=>setProjectId(e.target.value)}>{projects.map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select></label><label className="wide">{type==='task'?'Что должно быть сделано?':type==='ideas'?'В чём идея?':'Заголовок заметки'}<input name="title" autoFocus required placeholder={type==='task'?'Конкретный наблюдаемый результат':type==='ideas'?'Сформулируйте мысль одной строкой':'Короткое название'}/></label><label className="wide">{type==='task'?'Контекст':'Подробности'} <small>необязательно</small><textarea name="body" placeholder={type==='task'?'Почему это важно и что считать готовым?':'Раскройте мысль, пока она свежая'}/></label>{type==='task'&&<><label>Приоритет<select name="priority" defaultValue="Medium"><option value="High">Высокий</option><option value="Medium">Средний</option><option value="Low">Низкий</option></select></label><label>Дедлайн<div className="capture-date"><Calendar/><input name="deadline" type="date"/></div></label><label className="wide">Исполнитель<input name="assignee" defaultValue={userId} placeholder="Planner ID"/></label></>}<aside><i style={{background:current?.color}}/><span>{current?.outcome||current?.description||'Запись станет частью выбранного проекта'}</span></aside><button className="capture-submit"><Plus/>{type==='task'?'Добавить задачу':type==='ideas'?'Сохранить идею':'Сохранить заметку'}</button></form>}</motion.section></motion.div>
}
